server:
  port: ${GATEWAY_PORT:8080}

spring:
  application:
    name: oauth2-client-gateway
  security:
    oauth2:
      client:
        registration:
          bff-client:
            client-id: ${BFF_CLIENT_ID:bffClient}
            client-secret: ${BFF_SECRET_ID:bffSecret}
            authorization-grant-type: authorization_code
            redirect-uri: ${WEB_HOST:http://localhost:3000}/callback
            provider: spring
            scope: openid,profile
            client-name: bff-client
        provider:
          spring:
            issuer-uri: ${AUTHORIZATION_HOST:http://localhost:9000}
  cloud:
    gateway:
      default-filters:
      - TokenRelay=
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_PROTOCOL:http}://${EUREKA_USER:eureka}:${EUREKA_PASS:eureka_pass}@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
      fetch-registry: true
      register-with-eureka: true