server:
  port: 8000

spring:
  application:
    name: oauth2-client-gateway
  security:
    oauth2:
      client:
        registration:
          bff-client:
            client-id: ${BFF_CLIENT_ID:bffClient}
            client-secret: ${BFF_SECRET_ID:bffSecret}
            authorization-grant-type: authorization_code
            redirect-uri: ${WEB_HOST:http://localhost:3000}/callback
            provider: spring
            scope: openid,profile
            client-name: bff-client
        provider:
          spring:
            issuer-uri: ${AUTHORIZATION_HOST:http://localhost:9000}
  cloud:
    gateway:
      routes:
      - id: resource
        uri: http://localhost:8001
        predicates:
        - Path=/graphql/**, /graphiql/**
        filters: 
        - TokenRelay=