server:
  port: 8000

spring:
  application:
    name: oauth2-client-gateway
  security:
    oauth2:
      client:
        registration:
          oidc-client:
            client-id: oidc-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8000/login/oauth2/code/{registrationId}"
            provider: spring
            scope: 
              - openid
              - profile
        provider:
          spring:
            issuer-uri: http://localhost:9000
  cloud:
    gateway:
      routes:
      - id: bff
        uri: http://localhost:8001
        predicates:
        - Path=/api/**
        filters: 
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - TokenRelay=
        - SaveSession
        - StripPrefix=1