server:
  port: 8000

spring:
  application:
    name: oauth2-client-gateway
  security:
    oauth2:
      client:
        registration:
          oidc-client:
            client-id: ${RESOURCE_CLIENT_ID:resourceClient}
            client-secret: ${RESOURCE_SECRET_ID:resourceSecret}
            authorization-grant-type: authorization_code
            redirect-uri: ${GATEWAY_HOST:http://localhost:8000}/login/oauth2/code/oidc-client
            provider: spring
            scope: openid,profile
            client-name: oidc-client
          bff-client:
            client-id: ${BFF_CLIENT_ID:bffClient}
            client-secret: ${BFF_SECRET_ID:bffSecret}
            authorization-grant-type: authorization_code
            redirect-uri: ${WEB_HOST:http://localhost:3000}/callback
            provider: spring
            scope: openid,profile
            client-name: bff-client
        provider:
          spring:
            issuer-uri: ${AUTHORIZATION_HOST:http://localhost:9000}
  cloud:
    gateway:
      routes:
#      - id: userinfo
#        uri: http://localhost:9000
#        predicates:
#        - Path=/userinfo
#        filters: 
#        - TokenRelay=
      - id: resource
        uri: http://localhost:8001
        predicates:
        - Path=/api/**
        filters: 
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - TokenRelay=
        - SaveSession
        - StripPrefix=1