server:
    port: 8001

spring:
    application:
        name: spring-graphql
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${AUTHORIZATION_HOST:http://localhost:9000}
    graphql:
        graphiql:
            enabled: false
    data:
        r2dbc:
            repositories:
                enabled: true
    r2dbc:
        url: r2dbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5433}/${DATABASE_NAME:postgres_db}
        username: ${DATABASE_USER:postgres}
        password: ${DATABASE_PASSWORD:postgres_pass}