server:
    port: ${GRAPHQL_PORT:8081}

spring:
    application:
        name: spring-graphql
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${AUTHORIZATION_HOST:http://localhost:9000}
    graphql:
        graphiql:
            enabled: true
    data:
        r2dbc:
            repositories:
                enabled: true
    r2dbc:
        url: r2dbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5433}/${DATABASE_NAME:postgres_db}
        username: ${DATABASE_USER:postgres}
        password: ${DATABASE_PASSWORD:postgres_pass}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_PROTOCOL:http}://${EUREKA_USER:eureka}:${EUREKA_PASS:eureka_pass}@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
      fetch-registry: true
      register-with-eureka: true